### ISSUE TITLE
Swift 3 ?

### ISSUE THREAD

**Issue by zois** [gokulgovind/GLInAppPurchase#2]
Is this Swift3 compatible? I get lot's of errors when installing this.

**Comment by gokulgovind** [comment]
Just now updated,Please check it. Once done let me know.

**Comment by zois** [comment]
Great, solved. Also update your pod so it can pick up the latest. Otherwise one need to use:
pod 'GLInAppPurchase', :git => 'https://github.com/gokulgovind/GLInAppPurchase.git'

Thanks, very nice lib!

Regards
