### ISSUE TITLE
Cannot add text to displayContent

### ISSUE THREAD

**Issue by rlee1990** [gokulgovind/GLInAppPurchase#7]
Cannot change the banner color. An index out of range error pops up for 
`let attributeDescription = NSMutableAttributedString(string: String("\(tempContainer[0])\n\(tempContainer[1])"))`

**Comment by rlee1990** [comment]
Sorry looks like the issue was with me adding text with the displayContent.

**Comment by gokulgovind** [comment]
@rlee1990  No problem, If you found any other issues feel free to open a Issue.
